before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: binary
    format: binary
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x64{{ end }}
      {{- if eq .Arch "386" }}x86{{ end }}
      {{- if eq .Arch "arm64" }}arm64{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
