before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cursor-id-modifier
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64      # Intel 64-bit
      - arm64      # Apple Silicon/ARM64
      - "386"      # Intel 32-bit
    ignore:
      - goos: darwin
        goarch: "386"    # No 32-bit support for macOS
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

    # Build matrix
    matrix:
      # Special builds for macOS
      - goos: [darwin]
        goarch: [amd64]
        tags: ["intel"]
      - goos: [darwin]
        goarch: [arm64]
        tags: ["apple_silicon"]
      # Windows builds
      - goos: [windows]
        goarch: [amd64, "386"]
      # Linux builds
      - goos: [linux]
        goarch: [amd64, arm64, "386"]

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- with .Tags }}_{{ . }}{{ end }}
    files:
      - README.md
      - LICENSE
      - scripts/*    # Include installation scripts
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: x86
      amd64: x64
      arm64: arm64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Cursor ID Modifier {{ .Version }}
    
    ### Supported Platforms
    - Windows: x64, x86
    - macOS: Intel (x64), Apple Silicon (M1/M2)
    - Linux: x64, x86, ARM64
    
    See [CHANGELOG](CHANGELOG.md) for more details.
  footer: |
    **Full Changelog**: https://github.com/dacrab/cursor-id-modifier/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## Quick Installation
    
    **Linux/macOS**:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/dacrab/cursor-id-modifier/main/scripts/install.sh | sudo bash && cursor-id-modifier
    ```
    
    **Windows** (PowerShell Admin):
    ```powershell
    irm https://raw.githubusercontent.com/dacrab/cursor-id-modifier/main/scripts/install.ps1 | iex; cursor-id-modifier
    ```

snapshot:
  name_template: "{{ incpatch .Version }}-next"
