version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go mod verify

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.Commit}}'
      - -X 'main.date={{.Date}}'
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

# 添加构建时的项目设置
project_name: cursor-id-modifier

# 添加构建验证
builds_verify:
  - skip: false
    cmd: "{{.Binary}} --version"

# 改进发布配置
release:
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## Release {{.Tag}} ({{.Date}})
    
    See [CHANGELOG.md](CHANGELOG.md) for details.
  footer: |
    **Full Changelog**: https://github.com/owner/repo/compare/{{ .PreviousTag }}...{{ .Tag }}

archives:
  - id: binary
    format: binary
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x64{{ end }}
      {{- if eq .Arch "386" }}x86{{ end }}
      {{- if eq .Arch "arm64" }}arm64{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
