name: Auto Tag

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

permissions: write-all

jobs:
  auto-tag:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_latest_tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          set -e
          git fetch --tags || exit 1
          latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            new_version="v0.1.0"
          else
            major=$(echo $latest_tag | cut -d. -f1)
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)
            new_patch=$((patch + 1))
            new_version="$major.$minor.$new_patch"
          fi
          echo "version=$new_version" >> $GITHUB_OUTPUT
          echo "Generated version: $new_version"

      - name: Validate version
        run: |
          new_tag="${{ steps.get_latest_tag.outputs.version }}"
          echo "Validating version: $new_tag"
          if [[ ! $new_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $new_tag"
            exit 1
          fi
          echo "Version validation passed"

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          new_tag=${{ steps.get_latest_tag.outputs.version }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a $new_tag -m "Release $new_tag"
          git push origin $new_tag

      - name: Debug output
        run: |
          echo "Version output: ${{ steps.get_latest_tag.outputs.version }}"
          echo "Job outputs: ${{ toJSON(needs.auto-tag.outputs) }}"
          echo "::debug::Version value: ${{ steps.get_latest_tag.outputs.version }}"

  release:
    needs: auto-tag
    if: success() && needs.auto-tag.outputs.version != ''
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.auto-tag.outputs.version }}
    secrets: inherit
